apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todofrontend
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: todofrontend
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/todofrontend
    # Обратите внимание, что адрес поменялся – это новый параметр
    repoURL: {{ .Values.spec.source.appsRepoURL }}
    targetRevision: {{ .Values.spec.source.appsTargetRevision }}
    helm:
      valueFiles:
        # Указываем новый путь до только что созданного ключа
        - secrets+age-import:///helm-secrets-private-keys-apps/key.txt?../../values/todofrontend-prod.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
