# Первым делом импортируем каталог
apiVersion: resourcemanager.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: gitops
  annotations:
    crossplane.io/external-name: "b1gaqe811040e87odjgo"
spec:
  # этот параметр для безопасности
  # чтобы не удалить каталог при удалении ресурса из kubernetes
  deletionPolicy: Orphan
  forProvider:
    # default – стандартное название каталога по умолчанию
    # если ваш каталог называется по-другому – указываем это другое имя
    name: gitops
---
# Следующим шагом импортируем сеть
kind: Network
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: default
  annotations:
    crossplane.io/external-name: "enprl5t1nbhr1mfbtnbb"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: default
    # обратите внимание, что id каталога уже указывать не надо
    # достаточно использовать референс на другую сущность crossplane
    folderIdRef:
      name: gitops
---
# Импортируем подсеть default-ru-central1-b
kind: Subnet
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: default-ru-central1-b
  annotations:
    crossplane.io/external-name: "e2lh4rgsj07kmnlds9kk"
spec:
  forProvider:
    networkIdRef:
      name: default
    folderIdRef:
      name: gitops
    v4CidrBlocks:
      - 10.129.0.0/24  # берем из yc vpc subnet get default-ru-central1-b
---
kind: Zone
apiVersion: dns.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: yc-courses
  annotations:
    crossplane.io/external-name: "dns53sjrfdr4lja918r1"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: yc-courses
    zone: "familygram.online."
    public: true
    folderIdRef:
      name: gitops