apiVersion: v1
kind: Namespace
metadata:
  name: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь к чарту
    path: charts/crossplane
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      # проставляем путь к values-файлу
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/crossplane.yaml
  syncPolicy:
    automated: {}